### ISSUE TITLE
Tag a release.

### ISSUE THREAD

**Issue by bweston92** [monii/monii-container-interop-laravel#1]

**Comment by simensen** [comment]
@bweston92 Done! v1.0.0 was just tagged. Which project(s) are you working on that use(s) this package?

**Comment by bweston92** [comment]
I'm actually working on putting a few prooph components into Laravel starting with the service bus, Laravel's bus is a bit to tightly coupled. Http://GitHub.com/prooph



—

**Comment by simensen** [comment]
Awesome! I'm going to close this for now. Thanks for reaching out. How did you find this package, btw? Did you search Packagist or come across it some other way?

**Comment by bweston92** [comment]
Via packagist yes, surprisingly this is the only package. It is so disappointing Taylor will not implement this him-self. http://taylorotwell.com/interop-common-names/
